version: '3'
services:
  temporal:
    image: temporalio/auto-setup:1.22
    ports:
      - "7233:7233"
  cassandra:
    image: cassandra:4
    ports:
      - "9042:9042"
  minio:
    image: minio/minio
    command: server /data --console-address :9001
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"
      - "9001:9001"
